version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: flawcode_db
    environment:
      POSTGRES_DB: flawcode
      POSTGRES_USER: jatin123
      POSTGRES_PASSWORD: postgres123
    ports:
      - "5435:5432"
    volumes:
      - flawcode_db_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  flawcode_db_data: